### ISSUE TITLE
ゼロ除算でおちる

### ISSUE THREAD

**Issue by kykomi** [kinako4122/warikan#1]
Appleの計算機アプリは「エラー」とでますが、このアプリではクラッシュします。

**Comment by kinako4122** [comment]
issue作成ありがとうございます。
そうなんです。「わりかんちゃん」はとても繊細なのです！

**Comment by kinako4122** [comment]
@kykomi さん
修正しました＾＾！

**Comment by kykomi** [comment]
:100:
