### ISSUE TITLE
おんなのこの人数が全員より多い時にエラーメッセージを返す

### ISSUE THREAD

**Issue by kinako4122** [kinako4122/warikan#6]

**Comment by kinako4122** [comment]
新リポジトリで対応済み
https://github.com/kinako4122/warikanchan

**Comment by kinako4122** [comment]
@kykomi さん
I'm sorry but the repository named "warikanchan" that you have been watching were deleted because of the git error. But, I recreated. so please watch it~~~~!!! thank you.
https://github.com/kinako4122/warikanchan

**Comment by kykomi** [comment]
@kinako4122 
Sure.  
Now Watching! :eyes:
